version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./mnt/etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./laravel:/var/www/html
    ports:
      - "${DOCKER_MAP_PORT}:80"
    links:
      - laravel
  laravel:
    build: build/php
    # ports:
      # - "9000:9000"
      # - "8877:8877"
    volumes:
      # - ./mnt/laravel_queue.conf:/etc/supervisor/conf.d/laravel_queue.conf
      # - ./mnt/etc/logrotate.d/laravel:/etc/logrotate.d/laravel
      - ./laravel:/var/www/html
    environment:
      - TZ=Asia/Tokyo
      - APP_URL=http://localhost:${DOCKER_MAP_PORT}
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=user_password
      # - XDEBUG_CONFIG="remote_host=192.168.11.101"
    links:
      - mysql
  mysql:
    image: mysql:5.7.28
    # command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    volumes:
      - ./mnt/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql

